#!/usr/bin/env bash
# 00-prereqs.sh -- Validate required tools, AWS credentials, and input files.
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SETUP_DIR="${DEMO_DIR}/setup"
CREDS_FILE="${DEMO_DIR}/credentials.env"

PASS=0
FAIL=0

# --- Source credentials if available ---
echo "=== Checking credentials.env ==="
if [[ -f "${CREDS_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${CREDS_FILE}"
  echo "  [OK]  credentials.env loaded"
  PASS=$((PASS + 1))
else
  echo "  [FAIL] credentials.env not found"
  echo "         cp credentials.env.example credentials.env && vi credentials.env"
  FAIL=$((FAIL + 1))
fi

check() {
  local name="$1" cmd="$2" min_version="${3:-}"
  if command -v "$cmd" &>/dev/null; then
    local ver
    ver=$("$cmd" --version 2>&1 | head -1) || ver="unknown"
    echo "  [OK]  $name  ($ver)"
    PASS=$((PASS + 1))
  else
    echo "  [FAIL] $name  ('$cmd' not found)"
    FAIL=$((FAIL + 1))
  fi
}

echo "=== Checking required tools ==="
check "AWS CLI"            aws
check "Terraform"          terraform
check "openshift-install"  openshift-install
check "oc CLI"             oc
check "hcp CLI"            hcp
check "jq"                 jq
check "envsubst"           envsubst

echo ""
echo "=== Checking AWS credentials ==="
if aws sts get-caller-identity &>/dev/null; then
  ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
  echo "  [OK]  AWS account: ${ACCOUNT}"
  PASS=$((PASS + 1))
else
  echo "  [FAIL] AWS credentials not configured (run 'aws configure')"
  FAIL=$((FAIL + 1))
fi

echo ""
echo "=== Checking required files ==="
for f in pull-secret.json id_rsa.pub; do
  if [[ -f "${DEMO_DIR}/${f}" ]]; then
    echo "  [OK]  ${f}"
    PASS=$((PASS + 1))
  else
    echo "  [FAIL] ${f} not found in ${DEMO_DIR}/"
    FAIL=$((FAIL + 1))
  fi
done

echo ""
echo "=== Checking Terraform variables ==="
if [[ -f "${DEMO_DIR}/terraform/terraform.tfvars" ]]; then
  echo "  [OK]  terraform/terraform.tfvars exists"
  PASS=$((PASS + 1))
else
  echo "  [INFO] terraform/terraform.tfvars not found (auto-generated by 01-provision-infrastructure.sh)"
  PASS=$((PASS + 1))
fi

echo ""
echo "=== Checking AWS service quotas (m5.metal) ==="
REGION=$(grep -oP 'aws_region\s*=\s*"\K[^"]+' "${DEMO_DIR}/terraform/terraform.tfvars" 2>/dev/null || echo "us-east-2")
METAL_QUOTA=$(aws service-quotas get-service-quota \
  --service-code ec2 \
  --quota-code L-7212CCBC \
  --region "${REGION}" \
  --query 'Quota.Value' \
  --output text 2>/dev/null || echo "unknown")
if [[ "${METAL_QUOTA}" == "unknown" ]]; then
  echo "  [WARN] Could not query m5.metal quota (check manually)"
elif (( $(echo "${METAL_QUOTA} >= 288" | bc -l 2>/dev/null || echo 0) )); then
  echo "  [OK]  Running On-Demand Standard vCPU quota: ${METAL_QUOTA} (need 288 for 3× m5.metal)"
  PASS=$((PASS + 1))
else
  echo "  [WARN] Running On-Demand Standard vCPU quota: ${METAL_QUOTA} (need 288 for 3× m5.metal)"
  echo "         Request a quota increase if needed"
fi

echo ""
echo "=== Summary ==="
echo "  Passed: ${PASS}   Failed: ${FAIL}"
if [[ ${FAIL} -gt 0 ]]; then
  echo ""
  echo "Fix the failures above before continuing."
  exit 1
fi
echo "All prerequisites met."
