#!/usr/bin/env bash
# 01-provision-infrastructure.sh -- Create VPC, subnets, Route53 zone via Terraform.
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${DEMO_DIR}/terraform"
SETUP_DIR="${DEMO_DIR}/setup"
ENV_FILE="${SETUP_DIR}/.generated-infra.env"

source "${DEMO_DIR}/credentials.env"

echo "=== Provisioning AWS infrastructure ==="

# Auto-generate terraform.tfvars from credentials.env if it doesn't exist
if [[ ! -f "${TF_DIR}/terraform.tfvars" ]]; then
  echo "--- Generating terraform.tfvars from credentials.env ---"
  cat > "${TF_DIR}/terraform.tfvars" <<EOF
aws_region          = "${AWS_DEFAULT_REGION}"
cluster_name_prefix = "hcp-demo"
base_domain         = "${BASE_DOMAIN}"
enable_efs          = ${ENABLE_EFS_LIVE_MIGRATION:-false}
EOF
  echo "    Created ${TF_DIR}/terraform.tfvars"
fi

cd "${TF_DIR}"

if [[ ! -d .terraform ]]; then
  echo "--- Initializing Terraform ---"
  terraform init
fi

echo "--- Planning ---"
terraform plan -out=tfplan

echo "--- Applying ---"
terraform apply tfplan
rm -f tfplan

echo "--- Exporting outputs ---"
{
  echo "# Auto-generated by 01-provision-infrastructure.sh — do not edit"
  echo "export VPC_ID=$(terraform output -raw vpc_id)"
  echo "export BASE_DOMAIN=$(terraform output -raw base_domain)"
  echo "export AWS_REGION=$(terraform output -raw aws_region)"
  echo "export ROUTE53_ZONE_ID=$(terraform output -raw route53_zone_id)"
  echo "export TENANT_SG_ID=$(terraform output -raw tenant_security_group_id)"
  echo "export CROSS_CLUSTER_SG_ID=$(terraform output -raw cross_cluster_security_group_id)"

  echo "export PUBLIC_SUBNET_IDS=$(terraform output -json public_subnet_ids | jq -r 'join(",")')"
  echo "export PRIVATE_SUBNET_IDS=$(terraform output -json private_subnet_ids | jq -r 'join(",")')"
  echo "export TENANT_SUBNET_IDS=$(terraform output -json tenant_subnet_ids | jq -r 'join(",")')"
  echo "export AZ_TENANT_SUBNET_MAP='$(terraform output -json az_tenant_subnet_map)'"

  EFS_ID=$(terraform output -raw efs_filesystem_id 2>/dev/null || true)
  if [[ -n "${EFS_ID}" ]]; then
    echo "export EFS_FILESYSTEM_ID=${EFS_ID}"
  fi
} > "${ENV_FILE}"

# Re-tag subnets with actual cluster infra IDs (IPI adds these but terraform
# does not manage them, so a re-apply would remove them).
HUB_KC="${SETUP_DIR}/.generated-hub-kubeconfig"
VIRT_KC="${SETUP_DIR}/.generated-virt-kubeconfig"
if [[ -f "${HUB_KC}" || -f "${VIRT_KC}" ]]; then
  echo "--- Re-tagging subnets with cluster infra IDs ---"
  source "${ENV_FILE}"
  IFS=',' read -ra PUB_SUBS  <<< "${PUBLIC_SUBNET_IDS}"
  IFS=',' read -ra PRIV_SUBS <<< "${PRIVATE_SUBNET_IDS}"
  ALL_SUBS=("${PUB_SUBS[@]}" "${PRIV_SUBS[@]}")
  TAG_ARGS=()
  if [[ -f "${HUB_KC}" ]]; then
    HUB_INFRA=$(KUBECONFIG="${HUB_KC}" oc get infrastructure cluster \
      -o jsonpath='{.status.infrastructureName}' 2>/dev/null || true)
    [[ -n "${HUB_INFRA}" ]] && TAG_ARGS+=("Key=kubernetes.io/cluster/${HUB_INFRA},Value=shared")
  fi
  if [[ -f "${VIRT_KC}" ]]; then
    VIRT_INFRA=$(KUBECONFIG="${VIRT_KC}" oc get infrastructure cluster \
      -o jsonpath='{.status.infrastructureName}' 2>/dev/null || true)
    [[ -n "${VIRT_INFRA}" ]] && TAG_ARGS+=("Key=kubernetes.io/cluster/${VIRT_INFRA},Value=shared")
  fi
  if [[ ${#TAG_ARGS[@]} -gt 0 ]]; then
    aws ec2 create-tags --resources "${ALL_SUBS[@]}" \
      --tags "${TAG_ARGS[@]}" --region "${AWS_REGION}"
    echo "    Subnets re-tagged with: ${TAG_ARGS[*]}"
  fi
fi

echo ""
echo "Infrastructure provisioned. Outputs saved to:"
echo "  ${ENV_FILE}"
