#!/usr/bin/env bash
# 04-attach-secondary-nic.sh -- Create and attach secondary ENIs to bare-metal nodes.
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SETUP_DIR="${DEMO_DIR}/setup"
ENV_FILE="${SETUP_DIR}/.generated-infra.env"
VIRT_KUBECONFIG="${SETUP_DIR}/.generated-virt-kubeconfig"
GENERATED_NICS="${SETUP_DIR}/.generated-secondary-nics.env"

source "${DEMO_DIR}/credentials.env"
source "${ENV_FILE}"

echo "=== Attaching secondary ENIs to bare-metal nodes ==="

if [[ -f "${GENERATED_NICS}" ]]; then
  echo "Secondary NIC configuration already exists at ${GENERATED_NICS}."
  echo "Delete it to re-run."
  exit 0
fi

# Discover bare-metal instance IDs and AZs from OCP Machine objects.
# In OCP 4.21+ the AZ is in spec.providerID (aws:///AZ/INSTANCE-ID)
# rather than status.providerStatus.placement.availabilityZone.
INSTANCE_IDS=$(oc --kubeconfig="${VIRT_KUBECONFIG}" get machines -n openshift-machine-api \
  -o jsonpath='{range .items[*]}{.status.providerStatus.instanceId}{"\t"}{.spec.providerID}{"\n"}{end}' | \
  awk -F'\t' '{split($2, a, "/"); az=a[4]; if(az && $1) print $1"\t"az}')

if [[ -z "${INSTANCE_IDS}" ]]; then
  echo "ERROR: Could not discover instance IDs from OCP Machine objects."
  echo "Falling back to AWS tag discovery..."
  INSTANCE_IDS=$(aws ec2 describe-instances \
    --filters "Name=tag:kubernetes.io/cluster/virt-*,Values=owned" \
              "Name=instance-state-name,Values=running" \
    --query 'Reservations[].Instances[].[InstanceId, Placement.AvailabilityZone]' \
    --output text --region "${AWS_REGION}")
fi

echo "Discovered instances:"
echo "${INSTANCE_IDS}"
echo ""

AZ_SUBNET_MAP="${AZ_TENANT_SUBNET_MAP}"
ENI_IDS=""

while IFS=$'\t' read -r instance_id az; do
  [[ -z "${instance_id}" ]] && continue

  subnet_id=$(echo "${AZ_SUBNET_MAP}" | jq -r --arg az "${az}" '.[$az]')
  if [[ -z "${subnet_id}" || "${subnet_id}" == "null" ]]; then
    echo "WARNING: No tenant subnet found for AZ ${az}, skipping ${instance_id}"
    continue
  fi

  echo "--- Creating ENI for ${instance_id} in ${az} (subnet ${subnet_id}) ---"
  eni_id=$(aws ec2 create-network-interface \
    --subnet-id "${subnet_id}" \
    --groups "${TENANT_SG_ID}" \
    --description "HCP demo tenant network - ${instance_id}" \
    --query 'NetworkInterface.NetworkInterfaceId' \
    --output text \
    --region "${AWS_REGION}")

  echo "    ENI created: ${eni_id}"

  # Find the next available device index
  existing_count=$(aws ec2 describe-instances \
    --instance-ids "${instance_id}" \
    --query 'Reservations[0].Instances[0].NetworkInterfaces | length(@)' \
    --output text \
    --region "${AWS_REGION}")
  device_index="${existing_count}"

  echo "    Attaching as device index ${device_index}..."
  aws ec2 attach-network-interface \
    --network-interface-id "${eni_id}" \
    --instance-id "${instance_id}" \
    --device-index "${device_index}" \
    --region "${AWS_REGION}" \
    --output text

  echo "    Disabling source/dest check..."
  aws ec2 modify-network-interface-attribute \
    --network-interface-id "${eni_id}" \
    --no-source-dest-check \
    --region "${AWS_REGION}"

  ENI_IDS="${ENI_IDS}${eni_id},"
  echo "    Done."
  echo ""
done <<< "${INSTANCE_IDS}"

ENI_IDS="${ENI_IDS%,}"

{
  echo "# Auto-generated by 04-attach-secondary-nic.sh — do not edit"
  echo "export SECONDARY_ENI_IDS=\"${ENI_IDS}\""
} > "${GENERATED_NICS}"

echo "Secondary ENIs attached. IDs saved to:"
echo "  ${GENERATED_NICS}"
echo ""
echo "The secondary interface will appear as a new NIC on each node."
echo "Run 'oc debug node/<node> -- chroot /host ip link' to find the interface name."
